# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dmvkde <- function(y, x, bandwidth, weights, log_prob = FALSE, is_chol = FALSE) {
    .Call('kernelboot_cpp_dmvkde', PACKAGE = 'kernelboot', y, x, bandwidth, weights, log_prob, is_chol)
}

cpp_rmvkde <- function(n, x, bandwidth, weights, is_chol = FALSE) {
    .Call('kernelboot_cpp_rmvkde', PACKAGE = 'kernelboot', n, x, bandwidth, weights, is_chol)
}

cpp_dmvn <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('kernelboot_cpp_dmvn', PACKAGE = 'kernelboot', x, mu, sigma, log_prob)
}

cpp_rmvn <- function(n, mu, sigma) {
    .Call('kernelboot_cpp_rmvn', PACKAGE = 'kernelboot', n, mu, sigma)
}

cpp_duvkde <- function(y, x, bandwidth, weights, kernel = "gaussian", log_prob = FALSE) {
    .Call('kernelboot_cpp_duvkde', PACKAGE = 'kernelboot', y, x, bandwidth, weights, kernel, log_prob)
}

cpp_ruvkde <- function(n, x, bandwidth, weights, kernel = "gaussian", preserve_var = FALSE) {
    .Call('kernelboot_cpp_ruvkde', PACKAGE = 'kernelboot', n, x, bandwidth, weights, kernel, preserve_var)
}

