# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dmvkd <- function(x, y, bandwidth, weights, log_prob = FALSE, is_chol = FALSE) {
    .Call('kernelboot_cpp_dmvkd', PACKAGE = 'kernelboot', x, y, bandwidth, weights, log_prob, is_chol)
}

cpp_rmvkd <- function(n, y, bandwidth, weights, is_chol = FALSE) {
    .Call('kernelboot_cpp_rmvkd', PACKAGE = 'kernelboot', n, y, bandwidth, weights, is_chol)
}

cpp_dmvn <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('kernelboot_cpp_dmvn', PACKAGE = 'kernelboot', x, mu, sigma, log_prob)
}

cpp_rmvn <- function(n, mu, sigma) {
    .Call('kernelboot_cpp_rmvn', PACKAGE = 'kernelboot', n, mu, sigma)
}

cpp_duvkd <- function(x, y, bandwidth, weights, kernel = "gaussian", log_prob = FALSE) {
    .Call('kernelboot_cpp_duvkd', PACKAGE = 'kernelboot', x, y, bandwidth, weights, kernel, log_prob)
}

cpp_ruvkd <- function(n, y, bandwidth, weights, kernel = "gaussian", preserve_var = FALSE) {
    .Call('kernelboot_cpp_ruvkd', PACKAGE = 'kernelboot', n, y, bandwidth, weights, kernel, preserve_var)
}

