# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_noise <- function(x, weights, kernel = "gaussian", bandwidth = 1.0, preserve_var = FALSE) {
    .Call('kernelboot_add_noise', PACKAGE = 'kernelboot', x, weights, kernel, bandwidth, preserve_var)
}

cpp_dmvn <- function(x, mu, sigma, log_prob = FALSE) {
    .Call('kernelboot_cpp_dmvn', PACKAGE = 'kernelboot', x, mu, sigma, log_prob)
}

cpp_rmvn <- function(n, mu, sigma) {
    .Call('kernelboot_cpp_rmvn', PACKAGE = 'kernelboot', n, mu, sigma)
}

cpp_ruvkern <- function(n, data, weights, kernel = "gaussian", bw = 1.0, preserve_var = FALSE) {
    .Call('kernelboot_cpp_ruvkern', PACKAGE = 'kernelboot', n, data, weights, kernel, bw, preserve_var)
}

cpp_duvkern <- function(x, data, weights, kernel = "gaussian", bw = 1.0, log_prob = FALSE) {
    .Call('kernelboot_cpp_duvkern', PACKAGE = 'kernelboot', x, data, weights, kernel, bw, log_prob)
}

