name: CI

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v2
      - if: matrix.os == 'ubuntu-latest'
        name: Install system dependencies
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install packages
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
